### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by ArmorDarks** [thedaviddias/HTMLHint#214] opened 2017-07-22 08:35 UTC
Hi @yaniswang!

Thanks for that library, I think it solved a lot of issue for many people.

But for now it seems to be mostly abandoned, with lots of unclosed PRs and issues, outdated dependencies.

Is HTMLHint dead?

**Comment by jasonday** [comment] 2017-10-25 15:06
@yaniswang there are likely members of this community that can assist as collaborators.

**Comment by sinedied** [comment] 2017-10-30 13:48
@yaniswang If you do not plan to maintain this project that's fine, but please do not leave the community hanging, we can help with the maintenance as many of us depend on this package.

**Comment by peterparkers** [comment] 2017-12-12 06:46
Absolutely no. ^_^

**Comment by AndrewCraswell** [comment] 2017-12-31 11:57
Very disappointing. Especially seeing that VSCode was looking to recommend this project. There's so many open PRs too, lots of people interested in helping. At the least, it would be nice to see the existing work migrated to another project that enables more community participation.

**Comment by ArmorDarks** [comment] 2017-12-31 12:43
Some alternatives can be found [here](https://github.com/LotusTM/Kotsu/issues/268)

**Comment by tdmalone** [comment] 2017-12-31 23:20
@AndrewCraswell Just needs someone willing to take it on. =]

**Comment by thedaviddias** [comment] 2018-07-24 13:37
Hey @everyone! I know the issue is old, but I just wanted to tell you that I sent an email to the owner of the repo to ask if he could add me as a collaborator or give the ownership of the project. I'm willing to help the project to go further and work as everyone is expecting! 😉

**Comment by Shinigami92** [comment] 2018-07-31 12:00
First of all, it could stay with HTMLHint and become a fork of this repo. Then you can ask at npm if the old package can be replaced: https://docs.npmjs.com/misc/disputes

I would be very interested in helping to build a new HTMLHint or HTMLLint (hobby time)
Whereby a Hinter only provides annotations and a Linter also fixes and offers more configuration.
I would not call it HTML5*, because HTML* could be synonymous for HTML4 XHTML or HTML6, why directly limiting?

In a new Repo we can create new Proposals and build up from stretch maybe

**Comment by thedaviddias** [comment] 2018-07-31 12:10
I totally agree with having a "Linter" and not just a "Hinter". About HTML5, I thought about that too... Let see what other people think about.

Regarding the fact to build up from scratch, I would rather to start with something existing and updating it because it could take less time I think... but I may be wrong.

**Comment by Shinigami92** [comment] 2018-07-31 15:46
Ok, I reviewed GitHub a bit and found an existing Linter https://github.com/htmllint/htmllint
I do not know this linter and have not tried it

I think we now have 3 options:

1. Write a new (competing) HTMLLint
2. Make a fork of this HTMLHint, leave it behind and try it to stay compatible with the old config + extend the config to further new formats
3. Cooperate with the HTMLLint and push it (for example, there is no VSCode extension to support this linter)

---

In all 3 options I would like to rewrite it in TypeScript because I think that helps to find bugs and it is easier to maintain in the long term

**Comment by thedaviddias** [comment] 2018-07-31 16:13
@ArmorDarks I think the goal is not to go too far in a first time, but upgrading the existing. So the option 2 seems the most reasonable. And regarding TypeScript, even I love it too, plain JavaScript is the best in a first time, small steps for a biggest impact.

**Comment by Shinigami92** [comment] 2018-07-31 16:16
Agreed
Let me know when you start, so that I can help

**Comment by hacknug** [comment] 2018-07-31 19:04
Seems like no one mentioned [markuplint](https://github.com/markuplint/markuplint) so I guess I'll just leave it here in case it's helpful.

**Comment by vort3xxx** [comment] 2018-08-07 17:02
@hacknug, I evaluated markuplint for my angular application and it didn't go well when I plugged it in.  It did not seem to care for custom angular components, and had some of the indecipherable error messages.

**Comment by Shinigami92** [comment] 2018-08-07 17:04
@vort3xxx @hacknug I experienced the same thing
markuplint seems not to be ready in any way, it is heavily under construction

**Comment by thedaviddias** [comment] 2018-08-21 02:45
Hi @everyone!

In 8 days, if we don't have any news from @yaniswang, I'll be added to the list of contributors for HTMLHint! 🍾

It's going to be a lot of work, going through all bugs and PR... But I still believe, for now, this is the best thing to do. Moving to something else is probably too soon. First, reduce the among of issues, after, we can all decide the best direction to take!

**Comment by Shinigami92** [comment] 2018-08-21 03:00
@thedaviddias have you talked to Github?

**Comment by yaniswang** [comment] 2018-08-21 06:04
I'm sorry, i have no time for it.

Who can take over HTMLHint?

**Comment by coliff** [comment] 2018-08-21 06:06
Hi @yaniswang - great to hear from you! I'd love to be a contributor. I've been a HTMLHint user for many years and I'm very active on GitHub and manage and contribute to many open source projects.

**Comment by yaniswang** [comment] 2018-08-21 06:13
Who can be the owner of the project?

**Comment by coliff** [comment] 2018-08-21 06:17
I'd be very happy to be the project owner, but I'm fine with @thedaviddias being project owner if I can be on the projects team. :-)

**Comment by tdmalone** [comment] 2018-08-21 08:31
Welcome @yaniswang! I would vote for @thedaviddias as well given his enthusiasm and action thus far.

**Comment by thedaviddias** [comment] 2018-08-21 10:39
Hey @yaniswang! Awesome to hear from you, NPM and I were sending you various emails since a month. You can put me as owner of the project, and I'll add people that have been around to help in correcting bugs and issues we have today. @coliff and @tdmalone, thanks for the support, I eager to work with you on that project!

**Comment by thedaviddias** [comment] 2018-08-22 01:34
Probably last message on this issue, @yaniswang just transferred to me the ownership of the project. I'm going to create a Gitter channel for us to be able to exchange and update "Projects" on Github to see what needs to be done, prioritize etc... @ArmorDarks I think  that you can close this ticket 🤗

**Comment by yaniswang** [comment] 2018-08-22 01:52
@thedaviddias please give me your npm account

**Comment by thedaviddias** [comment] 2018-08-22 01:53
This is my NPM account: https://www.npmjs.com/~thedaviddias

**Comment by yaniswang** [comment] 2018-08-22 02:04
![image](https://user-images.githubusercontent.com/970390/44438673-c0327100-a5f2-11e8-95ce-5f7e3744aa6e.png)
Done

**Comment by yaniswang** [comment] 2018-08-22 02:07
Do you have godaddy account? i transfer the domain htmlhint.com to you

**Comment by thedaviddias** [comment] 2018-08-22 02:12
I don't have but you can eventually send me by email the code for the transfer I think... (my email: thedaviddias@gmail.com)

**Comment by yaniswang** [comment] 2018-08-22 02:26
i had send you the transefer code from email.

**Comment by Shinigami92** [comment] 2018-08-25 17:34
this issue can be closed

**Closed** 2018-08-26 15:55 UTC
