### ISSUE TITLE
Inline rules only work above the doctype

### ISSUE THREAD

**Issue by joeyparrish** [thedaviddias/HTMLHint#239] opened 2018-03-26 20:26 UTC
It seems that this override is honored:

```html
<!-- htmlhint style-disabled:false -->
<!DOCTYPE html>
<!-- Copyright foo -->
<html>
  <head>
    <style>
      body { background-color: white; }
    </style>
  </head>
</html>
```

But this is not:

```html
<!DOCTYPE html>
<!-- Copyright foo -->
<!-- htmlhint style-disabled:false -->
<html>
  <head>
    <style>
      body { background-color: white; }
    </style>
  </head>
</html>
```

Nor is this:

```html
<!DOCTYPE html>
<!-- Copyright foo -->
<html>
  <head>
    <!-- htmlhint style-disabled:false -->
    <style>
      body { background-color: white; }
    </style>
  </head>
</html>
```

According to https://stackoverflow.com/a/4897850, it seems that comments before doctype throw all versions of IE into quirks mode.

I think htmlhint should support inline rules either anywhere before the `<html>` tag or (better yet) anywhere at all.

If the rules were supported anywhere, I could document a rule override next to the thing that necessitates it.  This might cause some question as to the scope of that rule, though, so I would be just as happy with inline rules that were allowed between `<!DOCTYPE html>` and `<html>`.

Finally, it would be really helpful if htmlhint could log an error when inline rules are found in some unsupported place.  It is confusing to have them ignored, and I could not find documentation stating explicitly where they are supported.

Thanks!

**Comment by tdmalone** [comment] 2018-04-16 03:39
Duplicate of #210

**Closed** 2018-08-22 12:40 UTC
Labels: resolution: duplicate
